version: "2"

linters:
  default: none
  enable:
    - bidichk
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exhaustive
    - gocritic
    - gosec
    - ineffassign
    - ireturn
    - makezero
    - misspell
    - musttag
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign

  settings:
    revive:
      rules:
        - name: unused-parameter
          severity: warning
        - name: context-as-argument
          severity: warning

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: '_test\.go$'
        linters:
          - gosec
          - thelper
          - unparam

formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
